M_AC = M_AC or {}
M_AC.VERSION = '1.0.0'

M_AC.Severity = {
    INFO = 1,
    WARNING = 2,
    HIGH = 3,
    CRITICAL = 4,
}

M_AC.Flags = {
    EVENT_FLOOD = 'EVENT_FLOOD',
    COMMAND_FLOOD = 'COMMAND_FLOOD',
    ENTITY_FLOOD = 'ENTITY_FLOOD',
    TELEPORT_ANOMALY = 'TELEPORT_ANOMALY',
    SPEED_ANOMALY = 'SPEED_ANOMALY',
    COMBAT_ANOMALY = 'COMBAT_ANOMALY',
    EVENT_SPOOF = 'EVENT_SPOOF',
    ECONOMY_ANOMALY = 'ECONOMY_ANOMALY',
    RESOURCE_TAMPER = 'RESOURCE_TAMPER',
}
